### ISSUE TITLE
Insights derived in programming challenge

### ISSUE THREAD

**Issue by arunkpatra** [arunkpatra/athena#13]
## Ask

Try to derive the following insights.

- [x] Top selling cards by quantity and gross volume
- [x] Cards in the 90th percentile by gross sales volumes
- [x] Top selling cards by business model
- [x] Highest grossing merchants
- [x] Top cards by breakage as of today
- [x] Gross breakage by merchant as of today
- [x] Cards that are about to have breakage for a customer
- [x] Breakage forecast for Merchant, categorized by aspects like card category, customer segment, business model, card medium etc.

## Approach

- Query Redshift data for now. (will think about Spectrum later)
- Will optimize queries progressively. Will look at `distkey` and `sortkey` level optimizations subsequently.

## Outcome

- Set of tested queries and sample results
- Fine to test with a 'nano scale' dataset to start with.
- Load up a reasonable amount of data next, so that the insights are not badly skewed or look childish.

**Comment by sachinlala** [comment]
Looking good Arun. Please continue.

**Comment by arunkpatra** [comment]
Done for now.

**Comment by arunkpatra** [comment]
@sachinlala I added the two asks you had, updated the issue and am reopening it.

**Comment by arunkpatra** [comment]
@sachinlala Implemented logic for getting cards for a customer with unredeemed amounts. 

[WIP]Also added API methods for merchant related breakage forecasts based on card category(Shopping, Dining etc.), business model(Open-Loop, Close-Loop etc.), customer segment(Kid, Adult, Millennial, Senior etc.) and card medium(physical, digital)

**Comment by arunkpatra** [comment]
Implemented all queries/apis for merchant except based on customer segment and card medium(those would need a change to the data model; will reserve this for later)
