### ISSUE TITLE
Agree on key use cases

### ISSUE THREAD

**Issue by arunkpatra** [arunkpatra/athena#3]
Do these make sense, vis-a-vis objectives and schedule constraints?

1. As a card issuer, I need to see which cards would have a probability of breakage at what time and overall breakage value
2. As a card issuer, i need to know the schedule when notifications should be triggered, and the go ahead and approve the notification triggers for customers (system assisted, but human approved maybe)
3. See a simple user interface that gives me predicted escheatment risk value, and possible uplift from timely triggers.

**Comment by sachinlala** [comment]
Hi @arunkpatra - please see if this helps and can be incorporated as a value-added outcome.

https://gist.github.com/sachinlala/827662b6ce6835665608df096795a40e

Cheers.
Sachin

**Comment by sachinlala** [comment]
Arun - the 3 points above look good as the outcome.

**Comment by arunkpatra** [comment]
> Hi @arunkpatra - please see if this helps and can be incorporated as a value-added outcome.
> 
> https://gist.github.com/sachinlala/827662b6ce6835665608df096795a40e
> 
> Cheers.
> Sachin

Thanks @sachinlala , this helps. I opened up #14 to compile thoughts on breakage forecast. I'm yet to compile the wiki but kind of leaning towards one of the two approaches I mentioned there. My option 1 that I have in #14 is essentially alignes very closely with your gist :-)

Here's the [link to the wiki](https://github.com/arunkpatra/athena/wiki/Gift-Card-Breakage-Forecast-Approaches).

**Comment by arunkpatra** [comment]
> Arun - the 3 points above look good as the outcome.

@sachinlala I thought we were chasing scope as in #11 for now. But I will see how much I can finish. Essentially, all the work that I have gotten done is under [Programming Challenge](https://github.com/arunkpatra/athena/milestone/4) milestone. I have already closed a bunch of issues in that milestone.

**Comment by arunkpatra** [comment]
> Hi @arunkpatra - please see if this helps and can be incorporated as a value-added outcome.
> 
> https://gist.github.com/sachinlala/827662b6ce6835665608df096795a40e
> 
> Cheers.
> Sachin

Implemented the logic to forecast breakage in a simplified way. We look at historical breakage rates and then extrapolate for the current year.

**Comment by arunkpatra** [comment]
Closing for now.
